### ISSUE TITLE
Latex Equation Support

### ISSUE THREAD

**Issue by j-finger** [johansatge/obsidian-automatic-table-of-contents#13]
There seems to be no Automatic TOC generator that yet supports LaTeX in the headings. Please add this to your feature list. 
![image](https://github.com/johansatge/obsidian-automatic-table-of-contents/assets/80647966/05d98b8c-ff3d-41a8-a791-29ae646cf075)

**Comment by jasonbourne71** [comment]
I second the motion. I had to stop using Latex in higher level headings so I could actually find things.

**Comment by johansatge** [comment]
Hello!

This seems to be a limitation with Obsidian internal links 🤔 

Example:

```markdown
[[#Title with equation $C_{a}$]]
[[#Title with equation $C_{a}$|Title with equation $C_{a}$]]
[Title with equation $C_{a}$](#Title%20with%20equation%20$C_{a}$)

# Title with equation: $C_{a}$

Some text
```

No matter the link style (wikilink / wikilink with custom text / markdown link) the equation isn't rendered):

<img src="https://github.com/johansatge/obsidian-automatic-table-of-contents/assets/5699295/a2bbe2a5-7c15-4b7b-a3e8-3089851fc661" width="220px">

I'd suggest asking on the [Obsidian forum](https://forum.obsidian.md/) if this is an expected behavior or bug

**Comment by jasonbourne71** [comment]
OK :(. Thanks for the reply. I knew in my heart of hearts that this was an Obsidian thing. Appreciate your product, though.
